[package]
name = "casper-sidecar"
authors = ["George Williamson <george@casperlabs.io>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["casper-mainnet"]
casper-mainnet = ["casper-node/casper-mainnet"]

# todo Remove unused dependencies
[dependencies]
casper-node = { git = "https://github.com/casper-network/casper-node", branch = "dev"}
casper-types = { git = "https://github.com/casper-network/casper-node", branch = "dev"}
casper-hashing = { git = "https://github.com/casper-network/casper-node", branch = "dev"}
casper-client = { git = "https://github.com/casper-ecosystem/casper-client-rs", branch = "dev"}
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
sse-client = "1.1.1"
hex = "0.4.3"
rusqlite = {version = "0.25.3", features = ["bundled"]}
tokio = { version = "1", features = ["full"] }
warp = "0.3"
anyhow = {version = "1.0.44", default-features = false }
futures = "0.3.17"
clang = "1.0.3"
rocksdb = "0.18.0"
toml = "0.5.8"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-stream = "0.1.8"
uuid = "0.8.2"
rand = "0.8.5"

[patch.crates-io]
casper-execution-engine = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-node = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-hashing = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-types = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
