[package]
name = "casper-event-sidecar"
authors = ["George Williamson <george@casperlabs.io>"]
version = "0.1.0"
edition = "2018"

# todo Remove unused dependencies
[dependencies]
anyhow = {version = "1.0.44", default-features = false }
async-trait = "0.1.56"
bytes = "1.2.0"
casper-execution-engine = { git = "https://github.com/casper-network/casper-node", branch = "dev"}
casper-hashing = { git = "https://github.com/casper-network/casper-node", branch = "dev"}
casper-node = { git = "https://github.com/casper-network/casper-node", branch = "dev"}
casper-types = { git = "https://github.com/casper-network/casper-node", branch = "dev"}
derive_more = "0.99.7"
eventsource-stream = "0.2.3"
futures = "0.3.17"
hex = "0.4.3"
hex-buffer-serde = "0.3.0"
http = "0.2.1"
hyper = "0.14.4"
itertools = "0.10.3"
lazy_static = "1.4.0"
once_cell = "1"
rand = "0.8.3"
regex = "1.6.0"
reqwest = "0.11.11"
rusqlite = {version = "0.25.3", features = ["bundled"]}
schemars = { version = "=0.8.5", features = ["preserve_order", "impl_json_schema"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
smallvec = { version = "1", features = ["serde"] }
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.4", features = ["sync"] }
toml = "0.5.8"
tracing = "0.1"
tracing-subscriber = "0.3"
warp = { version = "0.3.0", features = ["compression"] }
wheelbuf = "0.2.0"
[patch.crates-io]
casper-execution-engine = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-node = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-hashing = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-types = { git = "https://github.com/casper-network/casper-node", branch = "dev" }

[dev-dependencies]
casper-node = { git = "https://github.com/casper-network/casper-node", branch = "dev", features = ["testing"]}
futures-util = "0.3.21"
pretty_assertions = "0.7.2"
reqwest = { version = "0.11.3", features = ["stream"] }
serial_test = "0.8.0"

[package.metadata.deb]
revision = "0"
assets = [
    ["./target/release/casper-event-sidecar", "/usr/bin/casper-event-sidecar", "755"],
    ["./resources/VAR_LIB_README.md", "/var/lib/casper/event-sidecar/README.md", "755"],
    ["./resources/ETC_README.md", "/etc/casper/event-sidecar/README.md", "755"],
    ["./resources/default_config.toml", "/etc/casper/event-sidecar/config.toml", "755"]
]
maintainer-scripts = "./resources/maintainer_scripts/debian"
extended-description = """
Package for Casper Event Sidecar
"""

[package.metadata.deb.systemd-units]
unit-scripts = "./resources/maintainer_scripts/casper_event_sidecar"
restart-after-upgrade = false

