[connection]
network = "Mainnet" # or Mainnet or Testnet
sse_filter = "main"
[connection.node.mainnet]
ip_address = "65.108.78.120"
sse_port=9999
rpc_port=7777
[connection.node.testnet]
ip_address="159.65.118.250"
sse_port=9999
rpc_port=7777
[connection.node.local]
ip_address="192.168.1.27"
sse_port=18101
rpc_port=11101

[storage]
db_path = "db/storage.db3"
kv_path = "db/kv_store"

[rest_server]
run = true
port = 3030

[ws_server]
run = true
port = 4040
