[connection]
network = "Testnet" # or Mainnet or Local
[connection.node.mainnet]
ip_address = "65.108.78.120"
sse_port=9999
[connection.node.testnet]
ip_address="159.65.118.250"
sse_port=9999
[connection.node.local]
ip_address="192.168.1.27"
sse_port=18101

[storage]
db_path = "./target/storage"
sse_cache = "./target/storage"

[rest_server]
port = 3030

[sse_server]
port = 19999
