[node_connection]
ip_address = "127.0.0.1"
sse_port = 18101

[storage]
storage_path = "./target/storage"
sqlite_file_name = "sqlite_database.db3"
# https://www.sqlite.org/compile.html#default_wal_autocheckpoint
sqlite_wal_autocheckpointing_interval = 1000
sse_cache_path = "./target/storage"

[rest_server]
ip_address = "127.0.0.1"
port = 17777

[sse_server]
ip_address = "127.0.0.1"
port = 19999