[node_connection]
ip_address="127.0.0.1"
sse_port=4444

[storage]
storage_path="./target/test_storage"
sqlite_file_name="sqlite_database.db3"
sse_cache_path="./target/test_storage"

[rest_server]
ip_address = "127.0.0.1"
port = 17777

[sse_server]
ip_address = "127.0.0.1"
port = 19999